### ISSUE TITLE
Minitest support?

### ISSUE THREAD

**Issue by maxp-edcast** [zeisler/active_mocker#117]
Hello, this looks like an awesome project. Our test base is incredibly slow, probably because of all the DB calls. I would like to integrate this tool, but ... we use minitest. Is it possible to use this with minitest?

**Comment by zeisler** [comment]
Thanks for your interest. Because it’s just ruby you can use it just fine with minitest.  The only thing you won’t get is the automatic constant stubbing. You’ll need to use ‘UserMock’ instead of ‘User’. An intergration for auto stubbing is also possible but the code needs to be written. I’d be  willing to work with anyone to make a PR.
