### ISSUE TITLE
ModelSchema::Assemble only examines files in root of configured directory.

### ISSUE THREAD

**Issue by tonyxyz** [zeisler/active_mocker#42]
It would be great to load and mock all classes under app/models/some/path/to/my_model.rb.

**Comment by zeisler** [comment]
Are you asking to be able to generate mocks from a custom path? That can be set by `ActiveMocker::Config.model_dir="app/models/some/path/to/**/*.rb"`

OR

From rake:
`MODEL_DIR="app/models/some/path/to/my_model.rb" rake active_mocker:build`

**Comment by markburns** [comment]
I'm picking this up from @tonyxyz in a different time zone. From reading his email it sounds like it's not about loading in a custom folder but rather picking up correctly all files defined in any sub directory of app/models.


To paraphrase:

We have Foo.  This inherits from Bar, which includes Bar::Baz amongst other things.

We think this is failing because Bar::Baz is never loaded.

The log reports that it cannot load Baz - actually it finds the file okay but does not complete the class loading process.

---- 


I will be having a look in detail today, but maybe that helps realise and or fix the problem sooner

**Comment by zeisler** [comment]
@markburns and @tonyxyz what version of active_mocker are you using?

**Comment by markburns** [comment]
Good shout. I would guess this issue is based on version `1.7.x` due to our app dependencies.
Which looking at it now looks like it is because of `active_mocker`'s dependency on `rake` `~> 10.0` and we have a dependency on `~> 11.0` elsewhere.

Will try a looser dependency in a fork of this gem to see if it allows an upgrade and fixes the issue, then a PR if so.

BTW does this sound like something you fixed since 1.7?

**Comment by markburns** [comment]
https://github.com/zeisler/active_mocker/pull/43 fixes rake issue. But I believe this issue still remains. Will update with more info if/when I find out.

**Comment by zeisler** [comment]
active_mocker v1.7.3 came out Dec 1, 2014. Migrating your project to v2.1.x should fix your issue since the generation engine has been completely rewritten. I will accept the change to reduce the rake dependancy and that will most likely be v2.1.4

**Comment by markburns** [comment]
@tonyxyz - when you come online I'd suggest we close this particular issue and determine more relevant PRs/issues as appropriate.

**Comment by tonyxyz** [comment]
Many thanks markburns, zeisler. This is working fine on the leading edge.
