### ISSUE TITLE
Integration with Factorygirl

### ISSUE THREAD

**Issue by Nikamura** [zeisler/active_mocker#5]
Hello,

I would like to ask if there are any future plans to integrate active_mocker with factorygirl?

**Comment by fatuhoku** [comment]
Hmm. Any chance that `factory_girl_rails` could be supported?

**Comment by zeisler** [comment]
@fatuhoku It may work just work with `factory_girl_rails`. I suggested plain `factory_girl` only because I like to run my active_mocker tests without the rails framework loaded, to increase it's speed, but there's nothing keeping you from loading it and using `factory_girl_rails`. Again I don't use factory_girl and don't plan to provide any special support for it, but there's reason why it shouldn't work.

**Comment by fatuhoku** [comment]
@zeisler hmm I ran into various issues trying to get Rails to recognise my ActiveRecord constants and eventually gave up. I've come around to your thinking — there's really no need to have Rails kicking around for unit tests!  I ended up just going `MyEntity.create(...)` rather than using `factory_girl`.

Thanks for the response.
